### ISSUE TITLE
Setting placeholder format breaks placeholder widget

### ISSUE THREAD

**Issue by retorquere** [troylutton/ckeditor#2]
If I set `format = '{{%placeholder%}}'`, it is inserted as normal text; this format is inserted as expected but it's not highlighted in yellow and I can write in the middle of it.

**Comment by troylutton** [comment]
Hi there @retorquere apologies for the late response.  Using the placeholder plugin is optional with placeholder select.  If you don't use the syntax that the placeholder module is expecting (the square brackets such as [[myplaceholder]]) then the text won't be highlighted.
